MainActivity/Controllers/PortalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MainActivity.Models;
using MainActivity.Services;
using Newtonsoft.Json;
using System;
using System.Xml;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace MainActivity.Controllers {
    public class PortalController : Controller {
        // Class Fields
        private readonly ICompany<ArticleContent> company;
        private const string ARTICLE_FILE = "ArticleContent.xml";
        private const string TAG = "PortalController";
        private const string MASTER = "Master";
        private const string ADMIN = "Admin";
        private readonly string rootPath;

        // Constructor
        public PortalController(IWebHostEnvironment hostEnvironment, ICompany<ArticleContent> company) {
            // Gets Project Root Path 
            this.rootPath = hostEnvironment.ContentRootPath;
            this.company = company;
        }



        //============================== Dashboard ============================== 

        // - GET
        [HttpGet]
        [Authorize(Roles = MASTER)]
        public IActionResult Dashboard() {
            try {
                // Request The Saved Cookie Data
                string loggedInAdmin = HttpContext.Request.Cookies[AccountController.COOKIE_KEY];
                // Deserialize Cookie Data 
                Administrator registeredAdmin = JsonConvert.DeserializeObject<Administrator>(loggedInAdmin);
                // Store The Cookie Data In ViewBag
                ViewBag.Administrator = new Administrator {
                    ID = registeredAdmin.ID,
                    Name = registeredAdmin.Name,
                    Email = registeredAdmin.Email,
                    Password = registeredAdmin.Password,
                    Role = registeredAdmin.Role
                };
            } catch (Exception exception) {
                // Show Error Message
                System.Diagnostics.Debug.WriteLine(TAG + exception.Message);
                return RedirectToAction("Index", "Home");
            }
            return View();

        }

        //============================== CREATE ============================== 


        // - GET
        [HttpGet]
        public IActionResult Create() => View();


        // - POST
        [HttpPost]
        public IActionResult Create(ArticleContent article) {
            if (ModelState.IsValid) {
                // Add The New Article Contents To SQLite Database
                company.Add(article);
                return RedirectToActionPermanent("Dashboard");
            }
            return View();
        }



        //============================== [EDIT] ============================== 

        // - GET
        [HttpGet]
        public IActionResult Edit() {
            if (company != null) {
                // Get A List Of All Saved Articles
                return View(company.GetAllReferences);
            }
            return View();

        }


        //============================== DELETE ============================== 
        public IActionResult Delete(int id) {
            if (ModelState.IsValid) {
                // Delete Article Based On The ID
                company.Delete(id);
            }
            return View();
        }


        //============================== SAVE ============================== 
        public IActionResult Save(int? id) {
            ArticleContent savedContent = company.GetReference(id);
            if (ModelState.IsValid) {
                // Save Article To The XML File
                SaveToXML(savedContent);
                return RedirectToAction("Index", "Home");
            }
            return View("Edit");

        }



        //============================== Controller Methods ============================== 
        private void SaveToXML(ArticleContent article) {
            // Creating Xml Settings For Our XML File
            XmlWriterSettings settings = new XmlWriterSettings() {
                Async = true,
                Indent = true,
                IndentChars = ("    "),
                CloseOutput = true,
                OmitXmlDeclaration = true

            };

            // Writes Contents To The New XML File 
            try {
                new System.Threading.Thread(() => {
                    using (var stream = System.IO.File.Open(ARTICLE_FILE, FileMode.Create, FileAccess.Write, FileShare.Read)) {
                        XmlWriter writer = XmlWriter.Create(stream, settings);
                        writer.WriteStartElement("ArticleContent");
                        writer.WriteElementString("Title", article.Title);
                        writer.WriteElementString("ParagraphTitle", article.ParagraphTitle);
                        writer.WriteElementString("ParagraphContent", article.ParagraphContent);
                        writer.WriteEndElement();
                        writer.Flush();
                    }

                }).Start();

            } catch (Exception exception) {
                System.Diagnostics.Debug.WriteLine(exception.Message);
            }
        }
    }// CLASS ENDS 
}

MainActivity/Views/Shared/_Add.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model MainActivity.Models.ArticleContent
<form asp-controller="Portal" asp-action="Save" method="post">

    <div asp-validation-summary="All"></div>
    <!--Article Title-->
    <div>
        <span asp-validation-for="Title"></span>
        <input asp-for="Title" placeholder="Title" />
    </div>
    <!--Paragraph Content-->
    <div>
        <span asp-validation-for="ParagraphContent"></span>
        <input asp-for="ParagraphContent" placeholder="Paragraph" />
    </div>

    <!--[Submit]-->
    <div>
        <input type="submit" value="Save" />
        <!--Action Will Render The Partial View-->
    </div>

</form>

MainActivity/Views/Shared/_Edit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<MainActivity.Models.ArticleContent>
<link href="@Url.Content("~/Styles/css/main.css")" rel="stylesheet" type="text/css" />


<!-- Title -->
<h1>@ViewBag.Tittle</h1>


<!-- How To Use Table With Models -->
<table id="article-table-layout" border="1">
    <!-- Table Row -->
    <tr class="table-row">
        <!-- Table Header -->
        <th>ID</th>
        <th>Tittle</th>
        <th>Paragraph</th>
        <th>Action</th>
        <th>Option</th>
    </tr>
    @if (Model != null) {
        @foreach (var content in Model) {
            <tr class="table-row" style="width:100%">
                <!-- Table Data -->
                <td>@content.ID</td>
                <td>@content.Title</td>
                <td>@content.ParagraphContent</td>
                <td>
                    <a asp-action="Delete" asp-route-id="@content.ID">Delete</a>
                </td>
                <td>
                    <a asp-action="Save" asp-route-id="@content.ID">Assign</a>
                </td>
            </tr>
        }
    }
</table>

MainActivity/Views/Shared/_Show.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model MainActivity.Models.ArticleContent



<link href="@Url.Content("~/Styles/css/main.css")" rel="stylesheet" type="text/css" />



<h4 hidden>@Html.DisplayFor(model => model.ID)</h4>

<section id="main-article-layout-wrapper">
    <h1 id="article-title">@Html.DisplayFor(model => model.Title)</h1>

    <h2 id="article-paragraph-title">@Html.DisplayFor(model => model.ParagraphTitle)</h2>

    <p id="article-paragraph-content">@Html.DisplayFor(model => model.ParagraphContent)</p>
</section>